### ISSUE TITLE
microsoft edge throws a security error when I try to draw the rasterization on a canvas

### ISSUE THREAD

**Issue by ryanackley** [cburgmer/rasterizeHTML.js#104]
Everything seems to work fine but when I go to draw the image on a canvas I get a securityerror in IE Edge. An XML error shows up in the console too. I'm thinking IE won't let the canvas read the svg from the blob?

**Comment by cburgmer** [comment]
You currently won't be able to read back from the canvas, most probably due to the security policy implementation of Edge. At least this was a similar bug in Chrome for a while.

Are you saying that you cannot draw the HTML to the canvas at all? AFAIK this should work at least for trivial cases of input.

You might want to dumb down your example and/or share it here. Happy to take a look at it!

**Comment by cburgmer** [comment]
Closing for now as there's no actionable thing. Feel free to re-open.
