### ISSUE TITLE
Intensive canvas refresh makes the previous frame not cleared before drawing another frame in canvas.

### ISSUE THREAD

**Issue by tsambora** [cburgmer/rasterizeHTML.js#105]
Hey first of all I must say I'm glad and thankful that you made this powerful library.

So I was using this to render some text to canvas and use some jQuery UI slider to toggle the font size. It worked well until I tested on an abusive behavior. When I slide the slider quickly from one value to another, the canvas render the next html without clearing the previous image. I'll post a picture below and some snippet if you need one. Is there anything I can do to tweak the performance?
![screen shot 2015-10-31 at 11 40 49 am](https://cloud.githubusercontent.com/assets/3667939/10861879/55d2a3e0-7fc4-11e5-9744-84cef3b6cbe5.png)

**Comment by cburgmer** [comment]
Hey, as far as I remember the library doesn't care at all about clearing the canvas. So I guess you have implemented something yourself to make it work in the first place?

In the example I have not done a good job, as it doesn't take care of the async nature of the drawing. If you look at https://github.com/cburgmer/rasterizeHTML.js/blob/master/examples/index.html#L55 then it clears the canvas before re-drawing, but if you do a lot of keystrokes, then eventually two clears will follow each other and then two re-draws will overlap. Maybe you have a similar issue?

**Comment by tsambora** [comment]
This is rather strange. I haven't write anything to clear the canvas before rendering either. But the canvas works perfectly when used in a non-abusive behavior. It shows the new resized content without overlapping the previous content, as if the previous content has been cleared.  

It looks like the HTML rendered within the canvas has a white background color and when being rendered in an abusive behavior it fails to render the container's background color. Is that possible?

**Comment by tsambora** [comment]
Yep it seems to be the problem. I tried giving the container a background color and the content doesn't overlap. It seems like if we don't specify the background color of the container it will have a white background color that won't be rendered if used in an abusive behavior. A rather strange symptom if i might say.

Also if you look at the top of the container. The yellow background is the canvas background. The content that is drawn in the canvas apparently have some margin. I think that is a different problem though. I might just be able to adjust the layout of my content to make it closer to the top of the canvas.

![screen shot 2015-11-02 at 3 14 10 pm](https://cloud.githubusercontent.com/assets/3667939/10877030/f0a294c8-8174-11e5-8f3e-d523202778e2.png)

**Comment by cburgmer** [comment]
The margin should be just the padding/margin of the body element, see #78. rasterizehtml can't tell if the HTML you passed is either a fragment or a full document, and so will always assume a body element, including the default styles for that element.

Your finding about the rapid re-rendering is that the background-color otherwise drawn by default is not applied any more? That is indeed funny. I am trying to reproduce here, but I can't. Please see the commit I made to branch issue105 and if you can reproduce your issue there I'd like to see how.

**Comment by tsambora** [comment]
Very well then. I'll try to reproduce the symptom and push it ASAP.

**Comment by tsambora** [comment]
Hey it seems like i can't push to the branch because i haven't been given the write permission.

I have reproduced the bug though. It happens when we declare a new canvas variable that refers to the <canvas id="canvas"></canvas> HTML element in each of the draw iteration. The drawing in that newly initiated canvas variable will not overlap until we set the time out to be really fast. Is this how it's supposed to be? If it is then it's pretty much my mistake for declaring new canvas variable in each draw.

**Comment by cburgmer** [comment]
Sorry, can you try pushing now? You should've gotten the rights.

**Comment by cburgmer** [comment]
I think the difference is not the new reference, but actually setting the width and/or height. Even if there is not change to the actual values, this operation clears the canvas for me under Firefox.

**Comment by tsambora** [comment]
Actually, you're right. It's the change of the size that caused it. So is it the expected behavior of the rendition?

**Comment by cburgmer** [comment]
At least this way it looks clear to me: Under "stress", the clearing for several calls happen together, while the asynchronous paint also happens together, but later, thus resulting in "over-painting". This is due to the asynchronous nature of the drawing.

A possible solution is to delay any other action on the canvas (e.g. resizing) to the callback being triggered. This would, I guess, require you to do the painting yourself, so as to do the resizing beforehand (e.g. https://github.com/cburgmer/rasterizeHTML.js/wiki/Examples#putting-the-html-on-the-canvas-ourselves).

**Comment by tsambora** [comment]
Sounds very clear to me. I think we can close this issue now. Thank you very much for your help. I really appreciate it.
