### ISSUE TITLE
Security error in Safari

### ISSUE THREAD

**Issue by scripting** [cburgmer/rasterizeHTML.js#171]
I'm getting a security error in Safari on a Mac or on IOS when I try to get a URL for a rendered canvas.

The error is:

> SecurityError: DOM Exception 18: An attempt was made to break through the security policy of the user agent.

The line of code that it fails on is:

`var urlImage = theCanvas.toDataURL ();`

Where theCanvas is the canvas that rasterizeHTML.drawHTML was drawing into.

There are no images in the HTML, nor any non-native fonts. I think I've eliminated anything that can legitimately be a security error. Works in Chrome.

Dave

**Comment by cburgmer** [comment]
Hey Dave, 

should be the known problem of Safari blocking reading from a canvas even for an empty `<foreignObject>` tag (https://github.com/cburgmer/rasterizeHTML.js/wiki/Limitations#safari). Remember that all your HTML is rendered embedded in a SVG).

Chrome used to have the same problems, but it was fixed by the Chrome devs a while back. Technically the browser wants to avoid the user session to leak through the contents of the canvas (say e.g. via visited CSS links), so Safari gets away easily but completely forbidding any read from a canvas once an SVG with a foreignObject was drawn. I'd say there's nothing you can do about it, as this is a hard rule in the rendering engine itself.

This doesn't mean you can't do nice stuff with the canvas though, but certainly limits what's possible. My only attempt at something fun so far was http://cburgmer.github.io/rasterizeHTML.js/jsconfus2014/#/step-21.

**Comment by scripting** [comment]
This is really weird because I do read the canvas in another app, Little Card Editor, and it works fine on Safari.

http://littlecardeditor.com/

You can try it out if you want. I use it all the time to post to Twitter and Facebook. It's a canvas. I get the contents of the canvas the same way I do it in the app I'm working on. 

So there's something about rasterizeHtml that's different from what Little Card Editor is doing. Or so it seems to me. ;-)

Dave

**Comment by scripting** [comment]
Update: Never mind I get it. It's the <foreignObject> inside the SVG that causes the problem. 

I guess what I have to do is check the browser at startup and show an error dialog if it's running on Safari. That's going to limit the utility because that's the built-in browser on iPhones. ;-(

Dave

**Comment by cburgmer** [comment]
Closing this. Hopefully Safari will support this in the future.

**Comment by LinusU** [comment]
Seems like `<foreignObject>` in the SVG is supported in iOS 13, but not on iOS 10. I haven't checked the versions in-between to figured out exactly which version added support yet...
