### ISSUE TITLE
Data URI Callback for save as file

### ISSUE THREAD

**Issue by riskihajar** [cburgmer/rasterizeHTML.js#58]
Hi, i was implement rasterizeHTML to render div in current document using drawHTML.
I got the result, but i need result as data URI/base_64 to save it as file.

on response callback, image src that uses blob URL.
i try convert it to data using this tutorial, but the return always empty.
http://stackoverflow.com/questions/14952052/convert-blob-url-to-normal-url

any solutions?

**Comment by respincruz** [comment]
I 'm in the same situation that riskihajar... I like save the file as base64 in the database. How i can obtain the base64 of image rasterize?? Please your help

**Comment by riskihajar** [comment]
just use toDataURL
```
var canvas = document.getElementById("canvas"),
    context = canvas.getContext('2d'),
    html_container = document.getElementById("thehtml"),
    html = html_container.innerHTML;

rasterizeHTML.drawHTML(html).then(function (renderResult) {
    context.drawImage(renderResult.image, 10, 25);

    base64data = canvas.toDataURL('image/png'); // this your base64 
});
```

**Comment by cburgmer** [comment]
If you need the image as png use riskihajar's solution. Note though that this will not work under Safari, due to buggy sandboxing there.

If you are happy with using the svg that is created in the background and used for rendering the png, try
```
var html_container = document.getElementById("thehtml"),
    html = html_container.innerHTML;

rasterizeHTML.drawHTML(html).then(function (renderResult) {
    console.log(renderResult.svg);
});
```

See https://github.com/cburgmer/rasterizeHTML.js/wiki/API#on-success for more information on the result.
